CREATE TABLE banks (
    bank_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name    VARCHAR2(255) NOT NULL,
    bank_code    VARCHAR2(50) UNIQUE
);

CREATE TABLE reviews (
    review_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id      NUMBER REFERENCES banks(bank_id),
    review_text  CLOB NOT NULL,
    review_date  DATE,
    rating       NUMBER(2,1),
    reviewer     VARCHAR2(255)
);